MY_OS_PATH_SYSTEM_SCRIPTS=$MY_OS_PATH_BASE/system-scripts

# Colors

MY_OS_COLOR_NONE='\033[0m'
MY_OS_COLOR_RED='\033[0;31m'
MY_OS_COLOR_GREEN='\033[0;32m'
MY_OS_COLOR_BLUE='\033[0;34m'
MY_OS_COLOR_YELLOW='\033[0;33m'

MY_OS_COLOR_WARN="$MY_OS_COLOR_YELLOW"
MY_OS_COLOR_ERR="$MY_OS_COLOR_RED"
MY_OS_COLOR_CMD="$MY_OS_COLOR_BLUE"
MY_OS_COLOR_INFO="$MY_OS_COLOR_GREEN"

MY_OS_SYSTEM=
