#!/bin/bash

perc=$(cat /sys/class/power_supply/BAT1/capacity)

stat=$(cat /sys/class/power_supply/BAT1/status)

audio_alert_low=~/Resources/Sounds/service-logout.oga
audio_alert_critically_low=~/Resources/Sounds/low_bat.mp3
audio_alert_full=~/Resources/Sounds/service-login.oga
icon_full=~/Resources/Icons/battery-full-solid.svg
icon_empty=~/Resources/Icons/battery-empty-solid.svg

if [ $stat = "Charging" ]
then
  if [ $perc -ge 90 ]
    then
    notify-send -u critical -i $icon_full "Battery is charged enough: $perc%. Unplug cable!"
    ffplay -nodisp -autoexit $audio_alert_full
  fi
  exit
fi

if [ $perc -lt 10 ]
then
	notify-send -u critical -i $icon_empty "Battery is EXTREMELY LOW: $perc%. Plug in the cable!"
  ffplay -nodisp -autoexit $audio_alert_critically_low
elif [ $perc -le 15 ]
then 
	notify-send -u critical -i $icon_empty "Battery is LOW: $perc%. Plug in the cable!"
  ffplay -nodisp -autoexit $audio_alert_low
fi

